CREATE UNDO TABLESPACE examen datafile 
'examen.dbf' size 25 M
AUTOEXTEND OFF;

CREATE USER Dbausuario IDENTIFIED BY "1234"  
DEFAULT TABLESPACE "EXAMEN"
TEMPORARY TABLESPACE "TEMP";

GRANT "DBA" TO Dbausuario ;
GRANT CONNECT, RESOURCE TO DBAuser;

CREATE TABLE CUSTOMERS(
IDCUSTOMERS NUMBER NOT NULL,
FIRST_NAME VARCHAR2(30),
LAST_NAME VARCHAR2(30),
EMAIL VARCHAR2(40),
ADDRESS VARCHAR2(40),
PHONE VARCHAR2(15),
RUT VARCHAR2(15)
);

ALTER TABLE CUSTOMERS ADD CONSTRAINT ID_CUSTOMERS_PK PRIMARY KEY(IDCUSTOMERS);


CREATE TABLE ACCOUNTS(
IDACCOUNTS NUMBER NOT NULL,
TYPEACCOUNTS VARCHAR2(30),
APERTURE_DATE DATE,
BALANCE NUMBER(15,2),
CUSTOMERSID NUMBER
);

ALTER TABLE ACCOUNTS ADD CONSTRAINT ID_ACCOUNTS_PK PRIMARY KEY(IDACCOUNTS);
ALTER TABLE ACCOUNTS ADD CONSTRAINT CUSTOMERS_ID_FK FOREIGN KEY(CUSTOMERSID) REFERENCES CUSTOMERS(IDCUSTOMERS);
ALTER TABLE ACCOUNTS ADD CONSTRAINT TYPE_ACCOUNTS_CK CHECK (TYPEACCOUNTS in('savings', 'loan', 'credit_card'));


CREATE OR REPLACE VIEW VISTA_UNO AS
SELECT CUST.FIRST_NAME, ACCO.IDACCOUNTS, ACCO.TYPEACCOUNTS, ACCO.APERTURE_DATE, ACCO.BALANCE
FROM CUSTOMERS CUST
INNER JOIN ACCOUNTS ACCO
ON CUST.IDCUSTOMERS = ACCO.CUSTOMERSID
WHERE ((TO_CHAR(ACCO.APERTURE_DATE,'YYYY')) BETWEEN '2013' AND '2017');

DESC VISTA_UNO;

CREATE PROCEDURE PR_DEVIATION AS

BEGIN
    SELECT STDDEV(BALANCE) FROM VISTA_UNO;
END;


